#!/bin/bash
# 生成 Shared/FeedConfig.swift（不进 git）：手机去哪读额度数据。
#   DANGO_FEED_BASE  例如 https://example.com/dango-feed
# 文件名取 ~/Library/Application Support/dango/phone-feed.secret。
set -euo pipefail
cd "$(dirname "$0")"
: "${DANGO_FEED_BASE:?DANGO_FEED_BASE 没设}"
SECRET=$(tr -dc 'a-f0-9' < "$HOME/Library/Application Support/dango/phone-feed.secret")
[ ${#SECRET} -ge 32 ] || { echo "phone-feed.secret 太短或不存在" >&2; exit 1; }
umask 077
cat > Shared/FeedConfig.swift <<SWIFT
// Generated by ios/gen-config.sh — not in git (the URL is a secret).
import Foundation
enum FeedConfig {
    static let url = URL(string: "${DANGO_FEED_BASE%/}/$SECRET.json")!
}
SWIFT
echo "wrote Shared/FeedConfig.swift"
