// Dump static ball geometry (head + eyes, transforms baked in) for the iOS
// widget, which draws the same balls with SwiftUI paths.
//
// Run: cargo run -p grok-ball --example frame_dump > ios/Shared/BallShapes.swift
use grok_ball::{Ball, BallOptions, DrawElement, Paint, ShapeKind};

const SHAPES: &[&str] = &[
    "blob", "wedge", "gem", "star", "cloud", "heart", "square", "drop", "whale", "cat",
];
const EMOTIONS: &[&str] = &["10", "19", "12", "34", "02", "14", "13", "03"];

fn frame(shape: ShapeKind, emotion: &str, color: &str) -> Vec<(String, Vec<(f32, f32)>, Paint)> {
    let mut ball = Ball::new(BallOptions {
        shape,
        color: Some(color.into()),
        eye_color: Some("#F5F2ED".into()),
        emotion: Some(emotion.into()),
        lite: true,
        autostart: false,
        ..Default::default()
    });
    ball.set_active(true);
    let f = ball.render_static(8000.0);
    f.elements
        .iter()
        .filter_map(|el| match el {
            DrawElement::Path(p) if p.visible && p.opacity > 0.01 => {
                let pts = p
                    .path
                    .verbs
                    .iter()
                    .filter_map(|v| match v {
                        grok_ball::PathVerb::MoveTo(x, y) | grok_ball::PathVerb::LineTo(x, y) => {
                            Some(p.transform.transform_point(*x, *y))
                        }
                        _ => None,
                    })
                    .collect();
                Some((p.id.clone().unwrap_or_default(), pts, p.fill.clone()))
            }
            _ => None,
        })
        .collect()
}

fn hex(p: &Paint) -> Vec<String> {
    match p {
        Paint::Solid(c) => vec![c.hex.clone()],
        Paint::RadialGradient(g) => g.stops.iter().map(|s| s.color.hex.clone()).collect(),
        Paint::LinearGradient(g) => g.stops.iter().map(|s| s.color.hex.clone()).collect(),
        Paint::None => vec![],
    }
}

fn main() {
    println!("// Generated by `cargo run -p grok-ball --example frame_dump`. Do not edit.");
    println!("// Static grok-ball frames (viewBox -15 -15 259 259): head outline + eyes per shape × emotion.");
    println!(
        "// headColors is non-nil only when the emotion paints the head itself (error red).\n"
    );
    println!("struct BallFrame {{ let head: [Double]; let eyes: [[Double]]; let headColors: [String]? }}\n");
    println!("enum BallShapes {{");
    println!("    static let frames: [String: BallFrame] = [");
    for name in SHAPES {
        let kind: ShapeKind = serde_json::from_str(&format!("\"{name}\"")).unwrap();
        for emo in EMOTIONS {
            let a = frame(kind, emo, "#D8A7A0");
            let b = frame(kind, emo, "#7FA8D6");
            let head = a.iter().find(|e| e.0 == "head").expect("head");
            let head_b = b.iter().find(|e| e.0 == "head").unwrap();
            let fixed = hex(&head.2) == hex(&head_b.2);
            let flat = |pts: &Vec<(f32, f32)>| {
                pts.iter()
                    .map(|(x, y)| format!("{x:.1},{y:.1}"))
                    .collect::<Vec<_>>()
                    .join(",")
            };
            let eyes: Vec<String> = a
                .iter()
                .filter(|e| e.0.starts_with("eye"))
                .map(|e| format!("[{}]", flat(&e.1)))
                .collect();
            let colors = if fixed {
                format!(
                    "[{}]",
                    hex(&head.2)
                        .iter()
                        .map(|h| format!("\"{h}\""))
                        .collect::<Vec<_>>()
                        .join(",")
                )
            } else {
                "nil".into()
            };
            println!("        \"{name}/{emo}\": BallFrame(head: [{}], eyes: [{}], headColors: {colors}),", flat(&head.1), eyes.join(","));
        }
    }
    println!("    ]");
    println!("}}");
}
