#!/usr/bin/env bash
#
# build-on-windows.sh —— 不经过 GitHub Actions，直接 SSH 到那台 Windows 上、在它本地构建。
#
# 为什么：私有仓库的 Actions 分钟数是**计费**的（windows-latest 2 倍、macos 10 倍），而我们
# 要的只是一个裸 exe —— 那台机器自己就编得出来。GitHub 退回它最本分的用途：代码托管
# （拉代码不花钱，只有跑 Actions 花）。
#
# 那边一次性准备（装齐之后，每次只用跑这个脚本；`--setup` 可以让脚本去装）：
#   1. Git for Windows            —— 版本戳要它（core/build.rs 里 `git rev-parse --short HEAD`）
#   2. Rust（rustup，MSVC 那条腿）—— 编译器
#   3. VS 2022 生成工具（VCTools 工作负载）—— link.exe + Windows SDK，Tauri 在 Windows 上必需
#   4. WebView2 runtime           —— Win10/11 装了 Edge 就有，一般不用管
# 不在这里做的：NSIS 安装包（要 Node + tauri CLI）。装机自动更新吃的是裸 exe
# （app/src/update.rs），安装器只有给一台全新机器装第一次时才要 —— 那台机器上装个 Node
# 跑一次 `npx @tauri-apps/cli@2 build` 就有了（Actions 那条路 2026-09-19 删了）。
#
# 代码怎么过去：默认在本地打一个 git bundle（**带 .git**，版本戳和 /version 里的 sha 才对得上），
# scp 到那边、从 bundle `git fetch` + `reset --hard`。全程走现成的 SSH 通道，不在那边存任何
# GitHub 凭据。想反过来让那边自己从 GitHub 拉，用 --from-github。
#
# 工作副本放哪：默认 `D:\code2\bridge`（`BRIDGE_WINDOWS_SRC` 能改）。bundle 和那几条 .cmd 帮手
# 落在 `%USERPROFILE%\.antigravity-bridge\` 下 —— 仓库目录里只放仓库本身，不留垃圾。
#
# 用法：
#   scripts/build-on-windows.sh                # 推代码 → 那边构建 → 装上并重启
#                                              #   那台第一次编约 12 分钟；之后哪怕代码一个字没动
#                                              #   也要 4 分钟上下（build.rs 每次都刷新编译时间戳，
#                                              #   core + app 跟着重编 —— 这是设计如此）
#   scripts/build-on-windows.sh --check        # 只看那边环境（git / cargo / MSVC / 工作副本 / 在跑的版本）
#   scripts/build-on-windows.sh --setup        # 一次性：装上面 1-3（几个 GB，很久，别在赶时间时跑）
#   scripts/build-on-windows.sh --build-only   # 只构建，不装不重启（看编译报错用这个）
#   scripts/build-on-windows.sh --from-github  # 那边直接从 GitHub 拉（要先在那边配好凭据）
#   scripts/build-on-windows.sh --offline      # 依赖都缓存过之后：cargo build --offline
#   scripts/build-on-windows.sh --force        # 那边工作副本脏了也照覆盖（默认拒绝，先让人看一眼）
#   BRIDGE_WINDOWS_HOST=other BRIDGE_WINDOWS_PORT=8046 scripts/build-on-windows.sh
#   BRIDGE_WINDOWS_SRC='E:\somewhere\bridge' scripts/build-on-windows.sh   # 换工作副本的位置
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)" # antigravity-bridge/（工作区）
REPO="$(cd "$ROOT/.." && pwd)"                         # 仓库根（bundle 从这里打）
HOST="${BRIDGE_WINDOWS_HOST:?用法：BRIDGE_WINDOWS_HOST=<主机> scripts/... 或 --host 传参}"
PORT="${BRIDGE_WINDOWS_PORT:-8045}"
GITHUB_URL="${BRIDGE_WINDOWS_REPO:-https://github.com/Jules-0409/dango.git}"

MODE="build" # build | check | setup
INSTALL=1
FROM_GITHUB=0
OFFLINE=""
FORCE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check) MODE="check"; shift ;;
    --setup) MODE="setup"; shift ;;
    --build-only) INSTALL=0; shift ;;
    --from-github) FROM_GITHUB=1; shift ;;
    --offline) OFFLINE="--offline"; shift ;;
    --force) FORCE=1; shift ;;
    --host) HOST="${2:?--host 后面要给主机名}"; shift 2 ;;
    --port) PORT="${2:?--port 后面要给端口}"; shift 2 ;;
    *) echo "不认识的参数：$1" >&2; exit 2 ;;
  esac
done

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

say() {
  if [[ "${1:-}" == "-n" ]]; then
    shift
    printf '%s' "$*"
  else
    printf '%s\n' "$*"
  fi
}
die() { printf '%s\n' "$*" >&2; exit 1; }

# 每一条远端动作都落成一个 .cmd 再执行：Windows 的 cmd 认不了纯 LF 的批处理，落盘时要换 CRLF；
# 文件里**只放 ASCII**（中途 chcp 会让 cmd 读错后面几行，push-update.sh 里踩过这个坑）。
# 本地底稿放在 `$TMP/<名字>.src`，占位符 `__XXX__` 在这里换成真值，远端文件名是 `<名字>.cmd`。
# 送进 sed 替换段之前先转义：反斜杠要翻倍（BSD sed 会把 `\U` 吃成 `U`，Windows 路径当场变残），
# `&`（代表整个匹配）和 `|`（我们的分隔符）也要转义。
sed_value() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/&/\\&/g' -e 's/|/\\|/g'
}

run_cmd() { # run_cmd <名字（不带后缀）> <占位符> <值> …
  local base="$1"
  shift
  local name="$base.cmd"
  awk '{ printf "%s\r\n", $0 }' "$TMP/$base.src" > "$TMP/$name"
  local expr=()
  while [[ $# -gt 0 ]]; do expr+=(-e "s|$1|$(sed_value "$2")|"); shift 2; done
  if [[ ${#expr[@]} -gt 0 ]]; then sed -i '' "${expr[@]}" "$TMP/$name"; fi
  scp -q "$TMP/$name" "$HOST:$REMOTE_POSIX/$name"
  ssh "$HOST" "\"$REMOTE_WIN\\$name\""
  return $?
}

# ---------- --setup：一次性装那三样（不用先有工作副本，所以放在取 %USERPROFILE% 之前）----------
if [[ "$MODE" == "setup" ]]; then
  say "在那台机器上装 Git / Rust / VS 生成工具 —— 几个 GB，可能要十几分钟，中途别断。"
  REMOTE_WIN='%USERPROFILE%\.antigravity-bridge'
  REMOTE_POSIX='%USERPROFILE%/.antigravity-bridge'
  ssh "$HOST" 'if not exist "%USERPROFILE%\.antigravity-bridge" mkdir "%USERPROFILE%\.antigravity-bridge"' ||
    die "ssh 到 $HOST 失败：那台机器是不是没开、或者反向隧道没起？（阿里云那边 22023 没人听就是这个）"
  cat > "$TMP/setup.src" <<'CMD'
@echo off
rem generated by scripts/build-on-windows.sh -- ASCII only, CRLF only.
setlocal enableextensions
set "PATH=%USERPROFILE%\.cargo\bin;%PATH%"
echo [1/3] Git for Windows
if exist "%ProgramFiles%\Git\cmd\git.exe" (echo already installed) else (
  winget install --id Git.Git -e --accept-package-agreements --accept-source-agreements
  if errorlevel 1 echo winget could not install git -- install it by hand: https://git-scm.com/download/win
)
echo [2/3] rustup (stable-msvc, minimal profile)
if exist "%USERPROFILE%\.cargo\bin\rustc.exe" (echo already installed) else (
  curl -sSfL -o "%TEMP%\rustup-init.exe" https://win.rustup.rs/x86_64 || exit /b 41
  "%TEMP%\rustup-init.exe" -y --profile minimal --default-toolchain stable-msvc || exit /b 42
)
echo [3/3] VS 2022 Build Tools + VCTools workload (the long one)
if exist "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" (
  "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
  if errorlevel 1 (
    curl -sSfL -o "%TEMP%\vs_BuildTools.exe" https://aka.ms/vs/17/release/vs_BuildTools.exe || exit /b 43
    "%TEMP%\vs_BuildTools.exe" --quiet --wait --norestart --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended || exit /b 44
  ) else (echo already installed)
) else (
  curl -sSfL -o "%TEMP%\vs_BuildTools.exe" https://aka.ms/vs/17/release/vs_BuildTools.exe || exit /b 43
  "%TEMP%\vs_BuildTools.exe" --quiet --wait --norestart --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended || exit /b 44
)
echo --- 装完自检 ---
set "PATH=%USERPROFILE%\.cargo\bin;%PATH%"
git --version
cargo --version
CMD
  run_cmd setup || die "装的过程中断了（退出码 ${?}）：上面的输出里有原因"
  say "装完了。接下来：scripts/build-on-windows.sh --check 再看一眼，然后直接不带参数跑一次构建。"
  exit 0
fi

# ---------- 远端路径：工作副本放哪由 BRIDGE_WINDOWS_SRC 说了算（默认 D:\code2\bridge），
# 别的辅助文件放 %USERPROFILE% 下（不在仓库里留垃圾）----------
WIN_HOME="$(ssh "$HOST" 'echo %USERPROFILE%' | tr -d '\r')" ||
  die "ssh 到 $HOST 失败：那台机器是不是没开、或者反向隧道没起？（阿里云那边 22023 没人听就是这个）"
[[ -n "$WIN_HOME" ]] || die "拿不到那边的 %USERPROFILE%：ssh 通了但回的是空"
WIN_HOME_POSIX="${WIN_HOME//\\//}"
REMOTE_WIN="${WIN_HOME}\\.antigravity-bridge\\scripts"
REMOTE_POSIX="${WIN_HOME_POSIX}/.antigravity-bridge/scripts"
SRC_WIN="${BRIDGE_WINDOWS_SRC:-D:\\code2\\bridge}"
SRC_PARENT_WIN="${SRC_WIN%\\*}"
BUNDLE_WIN="${WIN_HOME}\\.antigravity-bridge\\src\\bridge.bundle"
BUNDLE_POSIX="${WIN_HOME_POSIX}/.antigravity-bridge/src/bridge.bundle"
LOCAL_SHA="$(git -C "$REPO" rev-parse --short HEAD)"
LOCAL_SUBJECT="$(git -C "$REPO" log -1 --format=%s)"

ssh "$HOST" 'if not exist "%USERPROFILE%\.antigravity-bridge\scripts" mkdir "%USERPROFILE%\.antigravity-bridge\scripts"' >/dev/null
ssh "$HOST" 'if not exist "%USERPROFILE%\.antigravity-bridge\src" mkdir "%USERPROFILE%\.antigravity-bridge\src"' >/dev/null
ssh "$HOST" "if not exist \"$SRC_PARENT_WIN\" mkdir \"$SRC_PARENT_WIN\"" >/dev/null

# ---------- --check：只看环境 ----------
if [[ "$MODE" == "check" ]]; then
  say "看 ${HOST} 上的环境（本机 HEAD：${LOCAL_SHA} ${LOCAL_SUBJECT}）"
  cat > "$TMP/check.src" <<'CMD'
@echo off
rem generated by scripts/build-on-windows.sh -- ASCII only, CRLF only.
setlocal enableextensions
set "PATH=%USERPROFILE%\.cargo\bin;%PATH%"
echo --- machine ---
hostname
ver
echo --- git ---
git --version
echo --- rust ---
cargo --version
rustc --version
echo --- MSVC (link.exe / Windows SDK) ---
if exist "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" (
  "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
) else (echo no Visual Studio installer found)
echo --- working copy ---
if exist "__SRC__\.git" (git -C "__SRC__" log -1 --format="%h %s") else (echo no clone here yet)
echo --- bridge running on this box ---
curl -s --max-time 5 http://127.0.0.1:__PORT__/version
echo.
CMD
  run_cmd check "__SRC__" "$SRC_WIN" "__PORT__" "$PORT" || die "取环境信息失败（退出码 ${?}）"
  exit 0
fi

# ---------- 代码怎么过去 ----------
if [[ "$FROM_GITHUB" == 1 ]]; then
  say "那边直接从 ${GITHUB_URL} 拉（要它自己存好凭据）"
else
  say "打 bundle（HEAD ${LOCAL_SHA} ${LOCAL_SUBJECT}）→ scp 过去"
  # 只打 main 这一条线：那边是构建机，不需要本地那些杂七杂八的引用
  git -C "$REPO" bundle create "$TMP/bridge.bundle" main >/dev/null 2>&1 ||
    die "打 bundle 失败（仓库里有别的东西占着？）"
  scp -q "$TMP/bridge.bundle" "$HOST:$BUNDLE_POSIX" ||
    die "传 bundle 失败（到 ${HOST}:${BUNDLE_POSIX}）"
fi

# ---------- 构建（可选装上并重启）----------
say "在那边构建（cargo build --release -p antigravity-app${OFFLINE:+ $OFFLINE}）…"
{
  cat <<'CMD'
@echo off
rem generated by scripts/build-on-windows.sh -- ASCII only, CRLF only.
setlocal enableextensions
set "PATH=%USERPROFILE%\.cargo\bin;%PATH%"
set "SRC=__SRC__"
set "BUNDLE=__BUNDLE__"

echo [1/4] code
if not exist "%SRC%\.git" (
  git clone -b main "%BUNDLE%" "%SRC%" || exit /b 11
) else (
  cd /d "%SRC%" || exit /b 12
  git fetch "%BUNDLE%" main || exit /b 13
  git diff --quiet || exit /b 14
  git diff --cached --quiet || exit /b 15
  git reset --hard FETCH_HEAD || exit /b 16
)
git -C "%SRC%" log -1 --format="%h %s" || exit /b 17

echo [2/4] cargo build --release -p antigravity-app
cd /d "%SRC%\antigravity-bridge" || exit /b 20
cargo build --release __OFFLINE__ -p antigravity-app || exit /b 21
set "EXE=%SRC%\antigravity-bridge\target\release\antigravity-app.exe"
if not exist "%EXE%" exit /b 22
for %%F in ("%EXE%") do echo built: %%~zF bytes
CMD
  if [[ "$FROM_GITHUB" == 1 ]]; then
    cat <<'CMD'
echo (--from-github：代码现拉，没用 bundle)
CMD
  fi
  if [[ "$INSTALL" == 1 ]]; then
    cat <<'CMD'
echo [3/4] swap in the new exe
taskkill /IM antigravity-app.exe /F >nul 2>nul
ping -n 3 127.0.0.1 >nul
if not exist "%LOCALAPPDATA%\Antigravity Bridge" mkdir "%LOCALAPPDATA%\Antigravity Bridge"
copy /Y "%EXE%" "%LOCALAPPDATA%\Antigravity Bridge\antigravity-app.exe" >nul || exit /b 31
echo [4/4] start it back in the user session (ssh lands in session 0: no tray there)
schtasks /Create /F /TN BridgeAppRunOnce /TR "\"%LOCALAPPDATA%\Antigravity Bridge\antigravity-app.exe\" --port=__PORT__ --autostart" /SC ONCE /ST 23:59 /IT /RU "%USERNAME%" >nul || exit /b 32
schtasks /Run /TN BridgeAppRunOnce >nul || exit /b 33
ping -n 10 127.0.0.1 >nul
schtasks /Delete /F /TN BridgeAppRunOnce >nul 2>nul
echo installed and restarted.
CMD
  else
    cat <<'CMD'
echo (--build-only：没装、也没重启；exe 就在 %EXE%)
CMD
  fi
} > "$TMP/build.src"

set +e
if [[ "$FROM_GITHUB" == 1 ]]; then
  # 从 GitHub 拉的话 bundle 那条路不用走，远端自己 clone：把 fetch 那几步换掉
  sed -i '' -e 's|^  git clone -b main "%BUNDLE%" "%SRC%" .*$|  git clone -b main __GITHUB__ "%SRC%" \|\| exit /b 11|' "$TMP/build.src"
  sed -i '' -e 's|^  git fetch "%BUNDLE%" main .*$|  git fetch __GITHUB__ main \|\| exit /b 13|' "$TMP/build.src"
  run_cmd build "__SRC__" "$SRC_WIN" "__BUNDLE__" "$BUNDLE_WIN" "__OFFLINE__" "$OFFLINE" "__PORT__" "$PORT" "__GITHUB__" "$GITHUB_URL"
else
  run_cmd build "__SRC__" "$SRC_WIN" "__BUNDLE__" "$BUNDLE_WIN" "__OFFLINE__" "$OFFLINE" "__PORT__" "$PORT" "__GITHUB__" "$GITHUB_URL"
fi
CODE=$?
set -e

case "$CODE" in
  0) ;;
  14|15) die "那边的工作副本有未提交的改动（别闷声覆盖）：去 ${SRC_WIN} 看一眼，确认可以丢就加 --force" ;;
  13) die "那边 git fetch bundle 失败：bundle 是不是没传成功？（${BUNDLE_WIN}）" ;;
  21) die "那边编译失败（上面的报错就是它）。装环境没装全的话先跑 --setup，再看 --check" ;;
  *) die "那边构建/安装失败，退出码 ${CODE}（输出在上面）" ;;
esac

if [[ "$INSTALL" == 1 ]]; then
  say -n "那边现在跑的是："
  ssh "$HOST" "curl -s --max-time 5 http://127.0.0.1:$PORT/version" | head -c 300
  say ""
  say "（本机 HEAD 是 ${LOCAL_SHA}：上面 \"git\" 一栏对得上才算真的换上了）"
fi
